import { expect, test } from '@playwright/test'

test('transforma o diagnóstico em uma trilha de microetapas', async ({ page }) => {
  await page.route('**/rest/v1/rpc/**', route => route.fulfill({ status: 200, contentType: 'application/json', body: '[]' }))
  await page.route('**/functions/v1/**', route => route.fulfill({ status: 200, contentType: 'application/json', body: '{}' }))
  await page.addInitScript(() => localStorage.clear())
  await page.goto('/')
  await page.getByRole('button', { name: /iniciar minha trilha/i }).click()

  await expect(page.getByRole('heading', { name: /qual modelo/i })).toBeVisible()
  await page.getByRole('button', { name: /academia de bairro/i }).click()
  await expect(page.getByRole('heading', { name: /nome da academia/i })).toBeVisible()

  await page.getByPlaceholder('Ex.: Academia Movimento').fill('Academia Teste')
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()
  await page.getByLabel('Cidade *').fill('São José do Rio Preto')
  await page.getByRole('button', { name: /São José do Rio Preto SP/i }).click()
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()

  await expect(page.getByText('RADAR DE RECEITA DESBLOQUEADO')).toBeVisible()
  await expect(page.getByText(/benchmark de preços liberado/i)).toBeVisible()
  await expect(page.getByText(/pontos de diagnóstico/i)).toBeVisible()
  await page.screenshot({ path: 'test-results/radar-unlocked-mobile.png', fullPage: true })

  await page.getByRole('button', { name: /continuar minha trilha/i }).click()
  await expect(page.getByRole('heading', { name: /quantos alunos ativos/i })).toBeVisible()
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()
  await expect(page.getByText(/primeiro indicador revelado/i)).toBeVisible()
  await page.getByRole('button', { name: /continuar minha trilha/i }).click()
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()
  await page.getByRole('button', { name: /não aceito/i }).click()
  await expect(page.getByText(/oportunidade no radar/i)).toBeVisible()
  await page.getByRole('button', { name: /continuar minha trilha/i }).click()
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()
  await page.getByRole('button', { name: /confirmar e avançar/i }).click()
  await page.getByLabel('Seu nome *').fill('Gabriel')
  await page.getByLabel('E-mail *').fill('gabriel@example.com')
  await page.getByRole('button', { name: /revelar meu potencial/i }).click()
  await expect(page.getByText(/oportunidade anual identificada/i)).toBeVisible({ timeout: 5000 })
})
