import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, BadgeDollarSign, BarChart3, Check, ChevronRight, CircleDollarSign, Eye, Landmark, LoaderCircle, LockKeyhole, MapPin, Radar, ShieldCheck, Sparkles, Target, TrendingUp, Users } from 'lucide-react'
import { calculateRevenue } from './lib/calculations'
import { beginMarketResearch, completeSession, getPublicReport, saveProgress, startSession, storedSession, trackPageView } from './lib/supabase'
import { initialAnswers, type Answers, type RevenueReport, type Session } from './lib/types'

const brl = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 })
const num = new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 1 })
const STEPS = ['Local e perfil', 'Receita atual', 'Planos e preços', 'Wellhub', 'Vendas e retenção']
type NumberKey = { [K in keyof Answers]: Answers[K] extends number ? K : never }[keyof Answers]
type TextKey = { [K in keyof Answers]: Answers[K] extends string ? K : never }[keyof Answers]

function Money({ label, name, value, onChange, hint }: { label: string; name: NumberKey; value: number; onChange: (k: NumberKey, v: number) => void; hint?: string }) {
  return <label className="field"><span>{label}</span><div className="money"><b>R$</b><input inputMode="decimal" name={name} value={value || ''} onChange={e => onChange(name, Number(e.target.value))} /></div>{hint && <small>{hint}</small>}</label>
}
function Range({ label, name, value, min, max, step = 1, suffix = '', onChange }: { label: string; name: NumberKey; value: number; min: number; max: number; step?: number; suffix?: string; onChange: (k: NumberKey, v: number) => void }) {
  return <label className="range"><span>{label}<strong>{num.format(value)}{suffix}</strong></span><input type="range" name={name} value={value} min={min} max={max} step={step} onChange={e => onChange(name, Number(e.target.value))} /><div><small>{min}{suffix}</small><small>{max}{suffix}</small></div></label>
}

function App() {
  const [screen, setScreen] = useState<'home'|'quiz'|'loading'|'report'>('home')
  const [step, setStep] = useState(0)
  const [answers, setAnswers] = useState<Answers>(() => { try { return { ...initialAnswers, ...JSON.parse(localStorage.getItem('xray-receita-answers') || '{}') } } catch { return initialAnswers } })
  const [session, setSession] = useState<Session|null>(() => storedSession())
  const [remote, setRemote] = useState<{ answers: Answers; metrics: RevenueReport }|null>(null)
  const report = useMemo(() => calculateRevenue(answers), [answers])
  useEffect(() => {
    void trackPageView()
    const slug = location.pathname.match(/^\/r\/([a-f0-9]{64})$/i)?.[1]
    if (slug) void getPublicReport(slug).then(data => {
      const saved = data?.report as { answers?: Answers; metrics?: RevenueReport } | undefined
      if (saved?.answers && saved.metrics) { setRemote({ answers: saved.answers, metrics: saved.metrics }); setScreen('report') }
    })
  }, [])
  useEffect(() => { localStorage.setItem('xray-receita-answers', JSON.stringify(answers)) }, [answers])
  const setNumber = (key: NumberKey, value: number) => setAnswers(a => ({ ...a, [key]: value }))
  const setText = (key: TextKey, value: string) => setAnswers(a => ({ ...a, [key]: value }))
  const start = async () => { const created = await startSession(); setSession(created); setScreen('quiz'); void saveProgress(created, 0, answers, 'quiz_started') }
  const next = async () => {
    if (step === 0 && (!answers.email.includes('@') || !answers.city || !answers.state || !answers.gymName)) return
    await saveProgress(session, step + 1, answers)
    if (step === 0) void beginMarketResearch(session)
    if (step < STEPS.length - 1) { setStep(step + 1); window.scrollTo({ top: 0, behavior: 'smooth' }); return }
    setScreen('loading'); const slug = await completeSession(session, answers, report)
    if (slug) history.replaceState({}, '', `/r/${slug}`)
    setTimeout(() => setScreen('report'), 1900)
  }

  if (screen === 'home') return <main className="landing">
    <header className="nav"><div className="brand"><Radar/><span>GYM X-RAY</span><em>RECEITA</em></div><button className="ghost" onClick={start}>Começar diagnóstico <ArrowRight/></button></header>
    <section className="hero-home"><div className="hero-copy"><span className="eyebrow"><Sparkles/> RAIO-X FINANCEIRO DA SUA ACADEMIA</span><h1>Descubra quanto sua academia está <mark>deixando de faturar.</mark></h1><p>Transforme seus números em um plano direto para aumentar ticket, retenção e receita — sem precisar ampliar a estrutura.</p><button className="primary" onClick={start}>Calcular meu potencial de receita <ArrowRight/></button><small><ShieldCheck/> Diagnóstico confidencial · leva cerca de 6 minutos</small></div>
    <div className="opportunity-card"><div className="live"><i/> SIMULAÇÃO DO RESULTADO</div><span>Potencial anual identificado</span><strong>+ R$ 184.320</strong><div className="mini-chart"><i/><i/><i/><i/><i/><i/></div><p><TrendingUp/> 3 alavancas de crescimento encontradas</p></div></section>
    <section className="proof"><p>Você vai descobrir</p><div><article><CircleDollarSign/><strong>Ticket ideal</strong><span>Preço e mix de planos</span></article><article><Users/><strong>Receita perdida</strong><span>Churn e inadimplência</span></article><article><MapPin/><strong>Mercado local</strong><span>Preços e posicionamento</span></article><article><Target/><strong>Plano de ação</strong><span>O que fazer primeiro</span></article></div></section>
  </main>

  if (screen === 'loading') return <main className="loading"><div className="scan"><Radar/><i/></div><span>CRUZANDO SEUS INDICADORES</span><h1>Estamos encontrando dinheiro escondido na sua operação.</h1><div className="loading-list"><p><Check/> Ticket e mix de planos analisados</p><p><Check/> Retenção e inadimplência calculadas</p><p className="active"><LoaderCircle/> Consolidando plano de crescimento</p></div></main>
  if (screen === 'report') return <Report answers={remote?.answers || answers} report={remote?.metrics || report}/>

  return <main className="quiz"><header className="quiz-head"><div className="brand"><Radar/><span>GYM X-RAY</span><em>RECEITA</em></div><div><strong>{STEPS[step]}</strong><span>Etapa {step + 1} de {STEPS.length}</span></div></header><div className="progress"><i style={{ width: `${((step + 1) / STEPS.length) * 100}%` }}/></div>
    <section className="quiz-card"><button className="back" onClick={() => step ? setStep(step - 1) : setScreen('home')}><ArrowLeft/> Voltar</button>
    {step === 0 && <><span className="section-tag">COMEÇANDO PELO CONTEXTO</span><h1>Onde sua academia compete hoje?</h1><p className="lead">A localização será usada para pesquisar preços, modelos e presença no Wellhub na sua região.</p><div className="grid two"><label className="field"><span>Seu nome</span><input value={answers.ownerName} onChange={e => setText('ownerName', e.target.value)}/></label><label className="field"><span>Nome da academia *</span><input value={answers.gymName} onChange={e => setText('gymName', e.target.value)}/></label><label className="field"><span>E-mail para acessar o relatório *</span><input type="email" value={answers.email} onChange={e => setText('email', e.target.value)}/></label><label className="field"><span>WhatsApp</span><input value={answers.whatsapp} onChange={e => setText('whatsapp', e.target.value)}/></label><label className="field full"><span>Endereço</span><input value={answers.address} onChange={e => setText('address', e.target.value)} placeholder="Rua e número"/></label><label className="field"><span>Bairro</span><input value={answers.neighborhood} onChange={e => setText('neighborhood', e.target.value)}/></label><label className="field"><span>Cidade *</span><input value={answers.city} onChange={e => setText('city', e.target.value)}/></label><label className="field"><span>Estado *</span><input maxLength={2} value={answers.state} onChange={e => setText('state', e.target.value.toUpperCase())}/></label><label className="field"><span>Modelo</span><select value={answers.model} onChange={e => setText('model', e.target.value)}><option>Academia de bairro</option><option>Academia boutique / premium</option><option>Estúdio com atendimento personalizado</option><option>Academia de condomínio</option></select></label></div><Range label="Área útil aproximada" name="area" value={answers.area} min={50} max={3000} step={10} suffix=" m²" onChange={setNumber}/></>}
    {step === 1 && <><span className="section-tag">REALIDADE FINANCEIRA</span><h1>Vamos abrir os números da operação.</h1><p className="lead">Não precisa estar perfeito. Use a média dos últimos três meses.</p><Range label="Alunos ativos pagantes" name="activeStudents" value={answers.activeStudents} min={20} max={3000} step={10} onChange={setNumber}/><div className="grid two"><Money label="Faturamento total mensal" name="totalRevenue" value={answers.totalRevenue} onChange={setNumber}/><Money label="Receita com mensalidades" name="membershipRevenue" value={answers.membershipRevenue} onChange={setNumber}/><Money label="Outras receitas" name="otherRevenue" value={answers.otherRevenue} onChange={setNumber} hint="Personal, loja, avaliação, locação etc."/><Money label="Meta de faturamento mensal" name="revenueGoal" value={answers.revenueGoal} onChange={setNumber}/></div><div className="insight"><Eye/><div><b>Primeira leitura</b><p>Seu ticket realizado atual é de <strong>{brl.format(report.realizedTicket)}</strong> por aluno.</p></div></div></>}
    {step === 2 && <><span className="section-tag">ARQUITETURA DE PREÇOS</span><h1>Como seus planos estão organizados?</h1><p className="lead">Vamos comparar preço de tabela, prazo e o valor que realmente chega ao caixa.</p><div className="grid two"><Money label="Plano mensal" name="monthlyPrice" value={answers.monthlyPrice} onChange={setNumber}/><Money label="Plano trimestral (total)" name="quarterlyPrice" value={answers.quarterlyPrice} onChange={setNumber}/><Money label="Plano semestral (total)" name="semiannualPrice" value={answers.semiannualPrice} onChange={setNumber}/><Money label="Plano anual (total)" name="annualPrice" value={answers.annualPrice} onChange={setNumber}/></div><h3 className="subhead">Distribuição aproximada da base</h3><div className="grid two compact"><Range label="Mensal" name="monthlyMix" value={answers.monthlyMix} min={0} max={100} suffix="%" onChange={setNumber}/><Range label="Trimestral" name="quarterlyMix" value={answers.quarterlyMix} min={0} max={100} suffix="%" onChange={setNumber}/><Range label="Semestral" name="semiannualMix" value={answers.semiannualMix} min={0} max={100} suffix="%" onChange={setNumber}/><Range label="Anual" name="annualMix" value={answers.annualMix} min={0} max={100} suffix="%" onChange={setNumber}/></div><div className="grid two"><Range label="Inadimplência" name="defaultRate" value={answers.defaultRate} min={0} max={30} step={.5} suffix="%" onChange={setNumber}/><Range label="Taxa média de cartão" name="cardFee" value={answers.cardFee} min={0} max={12} step={.1} suffix="%" onChange={setNumber}/></div></>}
    {step === 3 && <><span className="section-tag">CANAIS CORPORATIVOS</span><h1>Qual é o papel do Wellhub na sua receita?</h1><p className="lead">O valor recebido é contratual; combinamos o dado real informado por você com a presença pública dos concorrentes.</p><div className="choice"><button className={answers.wellhub ? 'selected':''} onClick={() => setAnswers(a => ({...a, wellhub:true}))}><Check/> Sim, aceito Wellhub</button><button className={!answers.wellhub ? 'selected':''} onClick={() => setAnswers(a => ({...a, wellhub:false}))}><Check/> Não aceito Wellhub</button></div>{answers.wellhub && <div className="grid two"><Range label="Check-ins mensais" name="wellhubCheckins" value={answers.wellhubCheckins} min={0} max={5000} step={10} onChange={setNumber}/><Money label="Receita mensal do Wellhub" name="wellhubRevenue" value={answers.wellhubRevenue} onChange={setNumber}/></div>}<div className="insight"><Landmark/><div><b>{answers.wellhub ? 'Receita por check-in' : 'Oportunidade a validar'}</b><p>{answers.wellhub ? `Hoje cada check-in gera aproximadamente ${brl.format(report.wellhubPerCheckin)}.` : 'O relatório mostrará quais concorrentes próximos aparecem publicamente no benefício.'}</p></div></div></>}
    {step === 4 && <><span className="section-tag">MOTOR DE CRESCIMENTO</span><h1>Quantas pessoas entram — e quantas escapam?</h1><p className="lead">Crescer não é apenas vender mais. É impedir que a receita conquistada desapareça no mês seguinte.</p><div className="grid two compact"><Range label="Leads por mês" name="monthlyLeads" value={answers.monthlyLeads} min={0} max={1000} step={5} onChange={setNumber}/><Range label="Novos alunos por mês" name="newStudents" value={answers.newStudents} min={0} max={300} onChange={setNumber}/><Range label="Cancelamentos por mês" name="cancellations" value={answers.cancellations} min={0} max={300} onChange={setNumber}/><label className="field"><span>Último reajuste de preços</span><select value={answers.lastIncrease} onChange={e => setText('lastIncrease', e.target.value)}><option>Nos últimos 6 meses</option><option>Entre 6 e 12 meses</option><option>Mais de 12 meses</option><option>Nunca reajustei</option></select></label></div><div className={`insight ${report.netGrowth < 0 ? 'danger':''}`}><BarChart3/><div><b>Saldo mensal: {report.netGrowth >= 0 ? '+' : ''}{report.netGrowth} alunos</b><p>Seu churn estimado é de <strong>{num.format(report.churnRate * 100)}%</strong> ao mês.</p></div></div></>}
    <button className="primary continue" onClick={next}>{step === STEPS.length - 1 ? 'Gerar meu Raio-X de Receita' : 'Continuar'} <ArrowRight/></button><p className="save"><LockKeyhole/> Suas respostas são salvas automaticamente.</p></section></main>
}

function Report({ answers, report }: { answers: Answers; report: RevenueReport }) {
  const gap = Math.max(0, answers.revenueGoal - answers.totalRevenue)
  return <main className="report"><header className="report-nav"><div className="brand"><Radar/><span>GYM X-RAY</span><em>RECEITA</em></div><span>Diagnóstico de {answers.gymName}</span></header><section className="report-hero"><div><span className="eyebrow">OPORTUNIDADE ANUAL IDENTIFICADA</span><h1>Existe até <mark>{brl.format(report.annualOpportunity)}</mark> escondido na sua operação.</h1><p>Seu faturamento não depende apenas de colocar mais alunos para dentro. O maior ganho aparece na combinação entre preço, retenção e recuperação de receita.</p></div><div className="score"><span>EFICIÊNCIA DE RECEITA</span><strong>{report.score}</strong><small>de 100 pontos</small></div></section>
  <section className="report-body"><div className="metric-row"><article><span>FATURAMENTO ATUAL</span><strong>{brl.format(answers.totalRevenue)}</strong><small>por mês</small></article><ArrowRight/><article className="accent"><span>POTENCIAL MAPEADO</span><strong>{brl.format(report.projectedRevenue)}</strong><small>por mês</small></article><article className={gap ? 'alert':''}><span>DISTÂNCIA DA META</span><strong>{brl.format(gap)}</strong><small>{gap ? 'ainda precisa ser conquistado' : 'meta já alcançada'}</small></article></div>
  <h2>Onde a receita está escapando</h2><div className="levers"><article><BadgeDollarSign/><span>PREÇO E MIX</span><strong>+ {brl.format(report.monthlyPriceOpportunity)}/mês</strong><p>Ticket realizado de {brl.format(report.realizedTicket)} pode se aproximar de {brl.format(report.recommendedTicket)}.</p></article><article><Users/><span>RETENÇÃO</span><strong>+ {brl.format(report.monthlyRetentionOpportunity)}/mês</strong><p>Recuperando apenas 20% dos cancelamentos atuais.</p></article><article><ShieldCheck/><span>INADIMPLÊNCIA</span><strong>+ {brl.format(report.monthlyDefaultOpportunity)}/mês</strong><p>Estimativa conservadora de recuperação sobre a receita de planos.</p></article></div>
  <div className="verdict"><TrendingUp/><div><span>O NÚMERO QUE MUDA A DECISÃO</span><h2>Você pode reajustar seu ticket e perder até {report.churnTolerance} alunos sem reduzir a receita atual.</h2><p>Isso não é uma recomendação para perder alunos — é a margem financeira para executar uma transição de preço com segurança.</p></div></div>
  <section className="market-preview"><div><MapPin/><span>PESQUISA REGIONAL EM ANDAMENTO</span><h2>Preços e posicionamento em {answers.neighborhood ? `${answers.neighborhood}, ` : ''}{answers.city}</h2><p>Estamos verificando concorrentes, planos públicos e presença no Wellhub. O resultado será sempre acompanhado das fontes consultadas.</p></div><div className="radar-placeholder"><i/><i/><i/><i/><Radar/></div></section>
  <section className="locked"><LockKeyhole/><div><span>PLANO COMPLETO DE CRESCIMENTO</span><h2>Seu roteiro para sair de {brl.format(answers.totalRevenue)} e buscar {brl.format(Math.max(answers.revenueGoal, report.projectedRevenue))}/mês</h2><ul><li><Check/> Faixa recomendada de reajuste</li><li><Check/> Nova arquitetura de planos</li><li><Check/> Scripts de comunicação para alunos</li><li><Check/> Plano de execução em 90 dias</li></ul></div><button className="primary">Quero liberar meu plano <ChevronRight/></button></section>
  <p className="method">Estimativas gerenciais baseadas nos dados informados. A pesquisa regional diferencia fatos públicos, inferências e informações não encontradas. O diagnóstico não substitui contabilidade ou consultoria financeira.</p></section></main>
}
export default App
