create table public.xray_revenue_page_views (
  id uuid primary key default gen_random_uuid(),
  path text not null default '/',
  referrer text,
  metadata jsonb not null default '{}'::jsonb,
  viewed_at timestamptz not null default now()
);

create table public.xray_revenue_sessions (
  id uuid primary key default gen_random_uuid(),
  write_token_hash text not null,
  status text not null default 'started' check (status in ('started','in_progress','completed','abandoned')),
  current_step smallint not null default 0 check (current_step between 0 and 5),
  answers jsonb not null default '{}'::jsonb,
  email text,
  gym_name text,
  city text,
  state text,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.xray_revenue_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.xray_revenue_sessions(id) on delete cascade,
  event_name text not null,
  step smallint,
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create table public.xray_revenue_reports (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null unique references public.xray_revenue_sessions(id) on delete cascade,
  public_slug text not null unique,
  report_data jsonb not null,
  unlocked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.xray_revenue_market_research (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null unique references public.xray_revenue_sessions(id) on delete cascade,
  status text not null default 'queued' check (status in ('queued','processing','completed','failed')),
  location_query text not null,
  request_fingerprint text not null,
  result jsonb not null default '{}'::jsonb,
  sources jsonb not null default '[]'::jsonb,
  model text,
  openai_response_id text,
  error_message text,
  attempt_count integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index xray_revenue_sessions_status_updated_idx on public.xray_revenue_sessions(status, updated_at desc);
create index xray_revenue_sessions_email_idx on public.xray_revenue_sessions(lower(email)) where email is not null;
create index xray_revenue_events_session_time_idx on public.xray_revenue_events(session_id, occurred_at);
create index xray_revenue_events_name_time_idx on public.xray_revenue_events(event_name, occurred_at desc);

alter table public.xray_revenue_page_views enable row level security;
alter table public.xray_revenue_sessions enable row level security;
alter table public.xray_revenue_events enable row level security;
alter table public.xray_revenue_reports enable row level security;
alter table public.xray_revenue_market_research enable row level security;

revoke all on public.xray_revenue_page_views from anon, authenticated;
revoke all on public.xray_revenue_sessions from anon, authenticated;
revoke all on public.xray_revenue_events from anon, authenticated;
revoke all on public.xray_revenue_reports from anon, authenticated;
revoke all on public.xray_revenue_market_research from anon, authenticated;

create or replace function public.xray_revenue_track_view(p_path text default '/', p_referrer text default null)
returns void language plpgsql security definer set search_path = '' as $$
begin
  insert into public.xray_revenue_page_views(path, referrer)
  values (left(coalesce(nullif(trim(p_path), ''), '/'), 300), left(nullif(trim(p_referrer), ''), 1000));
end;
$$;

create or replace function public.xray_revenue_start_session()
returns table(session_id uuid, write_token text)
language plpgsql security definer set search_path = '' as $$
declare v_id uuid := gen_random_uuid(); v_token text := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
begin
  insert into public.xray_revenue_sessions(id, write_token_hash) values (v_id, encode(extensions.digest(v_token, 'sha256'), 'hex'));
  insert into public.xray_revenue_events(session_id, event_name, step) values (v_id, 'session_created', 0);
  return query select v_id, v_token;
end;
$$;

create or replace function public.xray_revenue_save_progress(p_session_id uuid, p_write_token text, p_current_step smallint, p_answers jsonb, p_event_name text default 'step_completed')
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if p_write_token is null or length(p_write_token) < 40 then return false; end if;
  update public.xray_revenue_sessions set
    current_step = greatest(current_step, least(5, greatest(0, p_current_step))),
    answers = coalesce(p_answers, '{}'::jsonb),
    email = nullif(left(trim(p_answers->>'email'), 320), ''),
    gym_name = nullif(left(trim(p_answers->>'gymName'), 200), ''),
    city = nullif(left(trim(p_answers->>'city'), 150), ''),
    state = nullif(left(upper(trim(p_answers->>'state')), 2), ''),
    status = case when status = 'completed' then status else 'in_progress' end,
    updated_at = now()
  where id = p_session_id and write_token_hash = encode(extensions.digest(p_write_token, 'sha256'), 'hex');
  if not found then return false; end if;
  insert into public.xray_revenue_events(session_id, event_name, step)
  values (p_session_id, left(coalesce(nullif(trim(p_event_name), ''), 'progress_saved'), 80), p_current_step);
  return true;
end;
$$;

create or replace function public.xray_revenue_complete_session(p_session_id uuid, p_write_token text, p_answers jsonb, p_report jsonb)
returns text language plpgsql security definer set search_path = '' as $$
declare v_slug text := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
begin
  if coalesce(trim(p_answers->>'email'), '') !~* '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$' then raise exception 'E-mail válido é obrigatório'; end if;
  update public.xray_revenue_sessions set answers = p_answers, email = left(trim(p_answers->>'email'), 320), gym_name = left(trim(p_answers->>'gymName'), 200), city = left(trim(p_answers->>'city'), 150), state = left(upper(trim(p_answers->>'state')), 2), current_step = 5, status = 'completed', completed_at = now(), updated_at = now()
  where id = p_session_id and write_token_hash = encode(extensions.digest(p_write_token, 'sha256'), 'hex');
  if not found then raise exception 'Sessão não autorizada'; end if;
  insert into public.xray_revenue_reports(session_id, public_slug, report_data) values (p_session_id, v_slug, coalesce(p_report, '{}'::jsonb))
  on conflict (session_id) do update set report_data = excluded.report_data, updated_at = now()
  returning public_slug into v_slug;
  insert into public.xray_revenue_events(session_id, event_name, step) values (p_session_id, 'quiz_completed', 5);
  return v_slug;
end;
$$;

create or replace function public.xray_revenue_get_report(p_public_slug text)
returns jsonb language sql security definer stable set search_path = '' as $$
  select jsonb_build_object('report', r.report_data, 'unlocked', r.unlocked, 'research_status', coalesce(m.status, 'not_started'), 'market_research', case when m.status = 'completed' then m.result else '{}'::jsonb end, 'sources', case when m.status = 'completed' then m.sources else '[]'::jsonb end)
  from public.xray_revenue_reports r left join public.xray_revenue_market_research m on m.session_id = r.session_id
  where r.public_slug = p_public_slug and length(p_public_slug) = 64;
$$;

revoke execute on function public.xray_revenue_track_view(text,text) from public;
revoke execute on function public.xray_revenue_start_session() from public;
revoke execute on function public.xray_revenue_save_progress(uuid,text,smallint,jsonb,text) from public;
revoke execute on function public.xray_revenue_complete_session(uuid,text,jsonb,jsonb) from public;
revoke execute on function public.xray_revenue_get_report(text) from public;
grant execute on function public.xray_revenue_track_view(text,text) to anon, authenticated;
grant execute on function public.xray_revenue_start_session() to anon, authenticated;
grant execute on function public.xray_revenue_save_progress(uuid,text,smallint,jsonb,text) to anon, authenticated;
grant execute on function public.xray_revenue_complete_session(uuid,text,jsonb,jsonb) to anon, authenticated;
grant execute on function public.xray_revenue_get_report(text) to anon, authenticated;

comment on function public.xray_revenue_start_session() is 'Public funnel endpoint. Returns a high-entropy write token; underlying tables remain inaccessible.';
